language: node_js
node_js:
    - "5"
script: client/node_modules/karma/bin/karma start client/test/karma.conf.js --single-run
before_install:
   - export CHROME_BIN=chromium-browser
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
before_script:
   - cd client
   - npm install
   - bower install
   - cd ..
